apiVersion: v1
kind: PersistentVolume
metadata:
  name: wl1-pv
spec:
  storageClassName: default
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - k8sm001.crayonbox.me
